---
deployment:
  tasks:
    - export DeploymentPath=/home/webevermk/public_html/grga.mk
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /bin/cp -R .output/* $DeploymentPath/
    - /bin/rm -f $DeploymentPath/.cpanel.yml
